/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGOSupervisor;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Ngo.EventRegistration;
import Business.Organization.EventOrganization;
import Business.Organization.NGOStaffOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Role.Role;
import Business.Role.EventOrganizer;
import Business.Role.NGOStaff;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EventWorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amruta
 */
public class NGOSupervisorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NGOAdminWorkAreaJPanel
     */
    private final UserAccount userAccount;
    private final EcoSystem system;
    private final Patient patient;
    private ArrayList<Enterprise> ngoEnt;
    public NGOSupervisorWorkAreaJPanel(UserAccount account,Patient patient,EcoSystem business) {
        initComponents();
        this.userAccount = account;
        this.system = business;
        this.patient = patient;
        this.ngoEnt = ngoEnt;
        populateEventOrganizerTable();
    }
    public void populateEventOrganizerTable()
    {
        DefaultTableModel model = (DefaultTableModel) eventTbl.getModel();
        model.setRowCount(0);
        for (Network network : system.getNetworkList())
        {
            String networkName=network.getName();
            ngoEnt=system.getEnterprise(networkName, Enterprise.EnterpriseType.NGO);
            //System.out.println(ngoEnt);
//            ArrayList<Enterprise> entList = system.getEnterprise(networkName, Enterprise.EnterpriseType.NGO);
//            ArrayList<UserAccount> eventList = new ArrayList<>();
//            ArrayList<UserAccount> eventOrganizerList = new ArrayList<>();
//            for (Enterprise ent : entList) {
//                for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
//                    if (org instanceof EventOrganization) {
//                        for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
//                        if (ua.getRole().getRoleType() == Role.RoleType.EventOrganizer) {
//                            eventList.add(ua);
//                        }
//                    }
//                    }
//                }
//            }

            for (Enterprise ent : this.ngoEnt) {
                for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                    if (org instanceof NGOStaffOrganization) {
                        for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                            if (ua.getRole().getRoleType() == Role.RoleType.NGOStaff) {
                                Object[] row = new Object[3];
                                row[0] = ua;
                                row[1] = network.getName();
                                row[2] = org;
                                model.addRow(row);
                            }
                        }
                    }
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txteventName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txteventLocation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txteventDescription = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        DateChooser = new com.toedter.calendar.JDateChooser();

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        eventTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NGO Staff", "Network", "Organization"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        eventTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(eventTbl);
        if (eventTbl.getColumnModel().getColumnCount() > 0) {
            eventTbl.getColumnModel().getColumn(2).setMinWidth(0);
            eventTbl.getColumnModel().getColumn(2).setPreferredWidth(0);
            eventTbl.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        jLabel1.setText("Event Name:");

        jLabel2.setText("Event Location:");

        jLabel3.setText("Event Description:");

        txteventDescription.setColumns(20);
        txteventDescription.setRows(5);
        jScrollPane2.setViewportView(txteventDescription);

        jLabel4.setText("Event Date:");

        submitButton.setText("Submit Event Details");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addComponent(txteventName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel4)
                                        .addGap(58, 58, 58)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txteventLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txteventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txteventLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitButton)
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
//        container.remove(this);
//
//        CardLayout layout = (CardLayout) container.getLayout();
//        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = eventTbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select an event", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String eventName=txteventName.getText();
        String eventLocation=txteventLocation.getText();
        Date eventDate=DateChooser.getDate();
        String eventDescription=txteventDescription.getText();
        if (eventName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter valid event name", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (eventLocation.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter valid event location", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (eventDescription.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter valid event description", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        UserAccount account = (UserAccount)eventTbl.getValueAt(selectedRow, 0);
        NGOStaffOrganization org = (NGOStaffOrganization)(eventTbl.getValueAt(selectedRow, 2));
        //System.out.println(org);
        EventRegistration event=new EventRegistration();
        event.setNgoOrganizer((NGOStaff)account.getRole());
        event.setEventName(eventName);
        event.setEventLocation(eventLocation);
        event.setEventDescription(eventDescription);
        event.setEventDate(eventDate);
        
        EventWorkRequest apptRequest = new EventWorkRequest(event);
        apptRequest.setStatus("Pending Confirmation");
        apptRequest.setReceiver(account);
        
        org.getWorkQueue().getWorkRequestList().add(apptRequest);
        //System.out.println(org.getWorkQueue().getWorkRequestList().add(apptRequest));
        JOptionPane.showMessageDialog(null, "Event description has been sent successfully to Event organizer", "Info Message", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable eventTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextArea txteventDescription;
    private javax.swing.JTextField txteventLocation;
    private javax.swing.JTextField txteventName;
    // End of variables declaration//GEN-END:variables
}
