/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Pharmacist;

import Business.EcoSystem;
import Business.Organization.PharmacyOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PharmacyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nidhi Goyal
 */
public class PharmacistWorkAreaJPanel extends javax.swing.JPanel {
    private final UserAccount userAccount;
    private final PharmacyOrganization phmcyOrganization;
    private final EcoSystem system;

    public PharmacistWorkAreaJPanel(UserAccount account, PharmacyOrganization phmcyOrg, EcoSystem system) {
        initComponents();
        this.userAccount = account;
        this.phmcyOrganization = phmcyOrg;
        this.system = system;

        pharmacistNameTxtField.setText(userAccount.getEmployee().getName());
        populatePharmacyRequestTable();
    }
    
    private void populatePharmacyRequestTable() {
        DefaultTableModel model = (DefaultTableModel) pharmacyTbl.getModel();
        model.setRowCount(0);
        
        if (phmcyOrganization.getWorkQueue() == null) {
            System.out.println("WorkQueue is NULL for " + phmcyOrganization.getName());
            return;
        }

        for (WorkRequest request : phmcyOrganization.getWorkQueue().getWorkRequestList()) {
            if (request == null) {
                continue;
            }

            // Do not show requests that are assigned to other pharmacists
            if (request.getReceiver() != null && !request.getReceiver().equals(userAccount)) {
                continue;
            }

            PharmacyWorkRequest labRequest = (PharmacyWorkRequest)request;
            Object[] row = new Object[4];
            row[0] = labRequest.getPatient().getName();
            row[1] = labRequest.getSender().getEmployee().getName();
            row[2] = labRequest.getMessage();
            row[3] = labRequest;

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignBtn = new javax.swing.JButton();
        processBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pharmacyTbl = new javax.swing.JTable();
        pharmacistNameTxtField = new javax.swing.JLabel();
        readyBtn = new javax.swing.JButton();

        assignBtn.setText("Assign");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });

        processBtn.setText("Process");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("PHARMACIST DASHBOARD");

        enterpriseLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        enterpriseLabel.setText("Pharmacist Name:");

        pharmacyTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient", "Doctor", "Medicine", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pharmacyTbl);

        pharmacistNameTxtField.setText("<value>");

        readyBtn.setText("Ready");
        readyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(assignBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(processBtn)
                        .addGap(18, 18, 18)
                        .addComponent(readyBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(pharmacistNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pharmacistNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignBtn)
                    .addComponent(processBtn)
                    .addComponent(readyBtn))
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        int row = pharmacyTbl.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Select a medicine request", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        PharmacyWorkRequest request = (PharmacyWorkRequest)pharmacyTbl.getValueAt(row, 3);
        request.setReceiver(userAccount);
        request.setStatus("Acknowledged");
        populatePharmacyRequestTable();
    }//GEN-LAST:event_assignBtnActionPerformed

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        int row = pharmacyTbl.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Select a medicine request", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        PharmacyWorkRequest request = (PharmacyWorkRequest)pharmacyTbl.getValueAt(row, 3);
        
        if (request.getReceiver() == null) {
            JOptionPane.showMessageDialog(null, "You need to assign the request to yourself before processing", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        request.setStatus("Processing");
        populatePharmacyRequestTable();
    }//GEN-LAST:event_processBtnActionPerformed

    private void readyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readyBtnActionPerformed
        int row = pharmacyTbl.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Select a medicine request", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }

        PharmacyWorkRequest request = (PharmacyWorkRequest)pharmacyTbl.getValueAt(row, 3);
        if (request.getReceiver() == null) {
            JOptionPane.showMessageDialog(null, "You need to assign the request to yourself before processing", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }

        request.setStatus("Ready For Pickup");
        request.setResolveDate(new Date());
        populatePharmacyRequestTable();
    }//GEN-LAST:event_readyBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignBtn;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pharmacistNameTxtField;
    private javax.swing.JTable pharmacyTbl;
    private javax.swing.JButton processBtn;
    private javax.swing.JButton readyBtn;
    // End of variables declaration//GEN-END:variables
}
